# Generated by Django 3.1.7 on 2022-09-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20220911_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='dop',
        ),
        migrations.AddField(
            model_name='product',
            name='yop',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
